# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-11 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=240)),
                ('priority', models.IntegerField(default=3)),
                ('status', models.BooleanField(default=0)),
                ('target_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('tasklist_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='tasklist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.TaskList'),
        ),
    ]
