# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-11 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='user_id',
        ),
        migrations.AddField(
            model_name='tasklist',
            name='password',
            field=models.CharField(default='password', max_length=128),
            preserve_default=False,
        ),
    ]
