# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-12 03:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tasklist_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tasklist_id',
            new_name='tasklist',
        ),
    ]
